### ISSUE TITLE
Finalizer is throwing in the chef tests on ruby 3.1.0

### ISSUE THREAD

**Issue by lamont-granquist** [chef/corefoundation#35]
Does not seem to affect ruby 3.0.3 but on ruby 3.1.0 we get a bunch of failures:

```
/Users/lamont/.asdf/installs/ruby/3.1.0/bin/bundle: warning: Exception in finalizer #<Proc:0x000000010a149a50 /Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40>
/Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40:in `release': :pointer argument is not a valid pointer (ArgumentError)
	from /Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40:in `block in finalize'
/Users/lamont/.asdf/installs/ruby/3.1.0/bin/bundle: warning: Exception in finalizer #<Proc:0x000000010a149c58 /Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40>
/Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40:in `release': :pointer argument is not a valid pointer (ArgumentError)
	from /Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40:in `block in finalize'
/Users/lamont/.asdf/installs/ruby/3.1.0/bin/bundle: warning: Exception in finalizer #<Proc:0x000000010a122478 /Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40>
/Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40:in `release': :pointer argument is not a valid pointer (ArgumentError)
	from /Users/lamont/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/corefoundation-0.3.10/lib/corefoundation/base.rb:40:in `block in finalize'
```

And the version of ffi that we're using:

```
    ffi (1.15.5)
```

**Comment by rishichawda** [comment]
@lamont-granquist corefoundation has a new release v0.3.13 which fixes this issue. Closing this for now.
